export const SHOP_URL = "https://vapedeliverybangalore.com";
export const WHATSAPP_NUMBER = "916282878843";
export const WHATSAPP_URL = "https://wa.me/916282878843?text=Hi! I want to order a vape in Bangalore.";

export const locations = [
  { slug: "btm-layout", name: "BTM Layout", sublocations: ["BTM 1st Stage", "BTM 2nd Stage", "Madiwala", "Gottigere"], metaTitle: "Vape Delivery BTM Layout Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in BTM Layout, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across BTM Layout, Bangalore." },
  { slug: "hsr-layout", name: "HSR Layout", sublocations: ["Sector 1", "Sector 2", "Sector 3", "Sector 4", "Sector 5", "Sector 6", "Sector 7"], metaTitle: "Vape Delivery HSR Layout Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in HSR Layout, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across HSR Layout, Bangalore." },
  { slug: "koramangala", name: "Koramangala", sublocations: ["1st Block", "2nd Block", "3rd Block", "4th Block", "5th Block", "6th Block", "7th Block", "8th Block"], metaTitle: "Vape Delivery Koramangala Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in Koramangala, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across Koramangala, Bangalore." },
  { slug: "indiranagar", name: "Indiranagar", sublocations: ["100 Feet Road", "CMH Road", "12th Main", "HAL 2nd Stage"], metaTitle: "Vape Delivery Indiranagar Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in Indiranagar, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across Indiranagar, Bangalore." },
  { slug: "whitefield", name: "Whitefield", sublocations: ["ITPL", "Varthur", "Kadugodi", "Hope Farm"], metaTitle: "Vape Delivery Whitefield Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in Whitefield, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across Whitefield, Bangalore." },
  { slug: "marathahalli", name: "Marathahalli", sublocations: ["ORR", "Spice Garden", "Doddanekundi", "Kundalahalli"], metaTitle: "Vape Delivery Marathahalli Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in Marathahalli, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across Marathahalli, Bangalore." },
  { slug: "electronic-city", name: "Electronic City", sublocations: ["Phase 1", "Phase 2", "Neeladri Road", "Hebbagodi"], metaTitle: "Vape Delivery Electronic City Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in Electronic City, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across Electronic City, Bangalore." },
  { slug: "jayanagar", name: "Jayanagar", sublocations: ["1st Block", "3rd Block", "4th Block", "9th Block"], metaTitle: "Vape Delivery Jayanagar Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in Jayanagar, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across Jayanagar, Bangalore." },
  { slug: "jp-nagar", name: "JP Nagar", sublocations: ["Phase 1", "Phase 2", "Phase 3", "Phase 4", "Phase 5", "Phase 6"], metaTitle: "Vape Delivery JP Nagar Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in JP Nagar, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across JP Nagar, Bangalore." },
  { slug: "hebbal", name: "Hebbal", sublocations: ["Manyata Tech Park", "Nagawara", "RT Nagar", "Thanisandra"], metaTitle: "Vape Delivery Hebbal Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in Hebbal, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across Hebbal, Bangalore." },
  { slug: "yelahanka", name: "Yelahanka", sublocations: ["Yelahanka New Town", "Yelahanka Old Town", "Kogilu", "Bagalur Road"], metaTitle: "Vape Delivery Yelahanka Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in Yelahanka, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across Yelahanka, Bangalore." },
  { slug: "rajajinagar", name: "Rajajinagar", sublocations: ["1st Block", "2nd Block", "3rd Block", "4th Block", "5th Block"], metaTitle: "Vape Delivery Rajajinagar Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in Rajajinagar, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across Rajajinagar, Bangalore." },
  { slug: "malleshwaram", name: "Malleshwaram", sublocations: ["8th Cross", "11th Cross", "Margosa Road", "Sampige Road"], metaTitle: "Vape Delivery Malleshwaram Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in Malleshwaram, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across Malleshwaram, Bangalore." },
  { slug: "banashankari", name: "Banashankari", sublocations: ["1st Stage", "2nd Stage", "3rd Stage", "4th Stage", "5th Stage", "6th Stage"], metaTitle: "Vape Delivery Banashankari Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in Banashankari, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across Banashankari, Bangalore." },
  { slug: "bellandur", name: "Bellandur", sublocations: ["Sarjapur Road", "ORR", "Kadubeesanahalli", "Iblur"], metaTitle: "Vape Delivery Bellandur Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in Bellandur, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across Bellandur, Bangalore." },
  { slug: "sarjapur-road", name: "Sarjapur Road", sublocations: ["Carmelram", "Halanayakanahalli", "Ambalipura", "Dommasandra"], metaTitle: "Vape Delivery Sarjapur Road Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online on Sarjapur Road, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across Sarjapur Road, Bangalore." },
  { slug: "mg-road", name: "MG Road", sublocations: ["Brigade Road", "Church Street", "Residency Road", "UB City"], metaTitle: "Vape Delivery MG Road Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online near MG Road, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across MG Road, Bangalore." },
  { slug: "kr-puram", name: "KR Puram", sublocations: ["Banaswadi", "Ramamurthy Nagar", "Hoodi", "ITPL Road"], metaTitle: "Vape Delivery KR Puram Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in KR Puram, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across KR Puram, Bangalore." },
  { slug: "hoodi", name: "Hoodi", sublocations: ["Hoodi Circle", "Whitefield Road", "Garudacharpalya", "Mahadevapura"], metaTitle: "Vape Delivery Hoodi Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in Hoodi, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across Hoodi, Bangalore." },
  { slug: "hennur", name: "Hennur", sublocations: ["Hennur Road", "Banaswadi", "Kalyan Nagar", "HBR Layout"], metaTitle: "Vape Delivery Hennur Bangalore | 30-45 Min | VapeDeliveryBangalore", metaDescription: "Buy vape online in Hennur, Bangalore. 30-45 min delivery. Order on WhatsApp.", description: "Fast vape delivery across Hennur, Bangalore." },
];

export function getLocationBySlug(slug: string) {
  return locations.find(l => l.slug === slug) || null;
}
