export interface Location {
  name: string;
  slug: string;
  sublocations: string[];
  localNote: string;
}

export const locations: Location[] = [
  {
    name: "BTM Layout",
    slug: "btm-layout",
    sublocations: ["BTM 1st Stage", "BTM 2nd Stage", "BTM 3rd Stage", "Madiwala", "Tavarekere", "Udupi Garden"],
    localNote: "BTM Layout is one of Bangalore's most densely populated residential zones — we cover every stage and corner.",
  },
  {
    name: "HSR Layout",
    slug: "hsr-layout",
    sublocations: ["Sector 1", "Sector 2", "Sector 3", "Sector 4", "Sector 5", "Sector 6", "Sector 7", "Agara", "Kudlu Gate"],
    localNote: "HSR Layout's grid layout makes navigation easy — our riders know every sector.",
  },
  {
    name: "Koramangala",
    slug: "koramangala",
    sublocations: ["1st Block", "2nd Block", "3rd Block", "4th Block", "5th Block", "6th Block", "7th Block", "8th Block", "ST Bed", "Ejipura"],
    localNote: "Koramangala is Bangalore's startup hub — fast delivery for the city's busiest professionals.",
  },
  {
    name: "Indiranagar",
    slug: "indiranagar",
    sublocations: ["HAL 1st Stage", "HAL 2nd Stage", "Domlur", "Old Airport Road", "Kodihalli", "Defence Colony"],
    localNote: "Indiranagar's buzzing café and bar culture makes us a natural fit — discreet delivery to your doorstep.",
  },
  {
    name: "Whitefield",
    slug: "whitefield",
    sublocations: ["ITPL", "Brookefield", "AECS Layout", "Kundalahalli", "Hope Farm", "Kadugodi", "Varthur", "Marathahalli"],
    localNote: "Whitefield's tech parks and residential pockets are fully covered — office or apartment, we reach you.",
  },
  {
    name: "Electronic City",
    slug: "electronic-city",
    sublocations: ["Phase 1", "Phase 2", "Doddathogur", "Neeladri Nagar", "Huskur", "Bommasandra"],
    localNote: "Electronic City's massive IT corridor keeps us busy — rapid delivery across both phases.",
  },
  {
    name: "Marathahalli",
    slug: "marathahalli",
    sublocations: ["Bridge Area", "Kalamandir", "Munnekollal", "Tulasi Theatre Road"],
    localNote: "Marathahalli's prime location between IT hubs means we're never far from you.",
  },
  {
    name: "Bellandur",
    slug: "bellandur",
    sublocations: ["Yemalur", "Devarabisanahalli", "Kariyammana Agrahara"],
    localNote: "Bellandur's growing residential and tech community gets priority delivery from us.",
  },
  {
    name: "Sarjapur Road",
    slug: "sarjapur-road",
    sublocations: ["Kaikondrahalli", "Kasavanahalli", "Harlur", "Ambalipura", "Carmelaram"],
    localNote: "Sarjapur Road's rapid development means new neighbourhoods — all of them on our delivery map.",
  },
  {
    name: "Yelahanka",
    slug: "yelahanka",
    sublocations: ["New Town", "Old Town", "Attur", "Kogilu", "Vidyaranyapura"],
    localNote: "Yelahanka's calm residential feel paired with our fast service is the perfect combo.",
  },
  {
    name: "Hebbal",
    slug: "hebbal",
    sublocations: ["RT Nagar", "Nagawara", "Manyata Tech Park Area", "Kempapura"],
    localNote: "Hebbal is Bangalore's northern gateway — Manyata Tech Park to RT Nagar, we've got you.",
  },
  {
    name: "Jayanagar",
    slug: "jayanagar",
    sublocations: ["1st Block", "2nd Block", "3rd Block", "4th Block", "5th Block", "6th Block", "7th Block", "8th Block", "9th Block"],
    localNote: "Jayanagar's classic Bangalore charm meets modern convenience — quick vape delivery, every block.",
  },
  {
    name: "JP Nagar",
    slug: "jp-nagar",
    sublocations: ["Phase 1", "Phase 2", "Phase 3", "Phase 4", "Phase 5", "Phase 6", "Phase 7", "Phase 8"],
    localNote: "JP Nagar's eight phases are all within our delivery radius — no phase left behind.",
  },
  {
    name: "Banashankari",
    slug: "banashankari",
    sublocations: ["Stage 1", "Stage 2", "Stage 3", "Stage 4", "Kathriguppe"],
    localNote: "Banashankari's well-planned layout makes our deliveries smooth and on-time, every time.",
  },
  {
    name: "Rajajinagar",
    slug: "rajajinagar",
    sublocations: ["1st Block", "2nd Block", "3rd Block", "4th Block", "5th Block", "6th Block"],
    localNote: "Rajajinagar is one of West Bangalore's most connected areas — our riders know every block.",
  },
  {
    name: "Malleshwaram",
    slug: "malleshwaram",
    sublocations: ["8th Cross", "Sampige Road", "Vyalikaval"],
    localNote: "Malleshwaram's heritage streets get modern convenience — discreet and fast delivery.",
  },
  {
    name: "MG Road",
    slug: "mg-road",
    sublocations: ["Brigade Road", "Church Street", "Residency Road", "Richmond Town", "Shanti Nagar"],
    localNote: "Central Bangalore's most premium corridor — we deliver to the heart of the city.",
  },
  {
    name: "KR Puram",
    slug: "kr-puram",
    sublocations: ["TC Palya", "Ramamurthy Nagar", "A Narayanapura"],
    localNote: "KR Puram's east Bangalore connectivity means fast routes and on-time delivery.",
  },
  {
    name: "Hoodi",
    slug: "hoodi",
    sublocations: ["Hoodi Circle", "Garudachar Palya"],
    localNote: "Hoodi's growing IT and residential mix is squarely in our delivery zone.",
  },

  {
    name: "The Leela Palace Bangalore",
    slug: "leela-palace-bangalore",
    sublocations: ["Old Airport Road", "HAL Area", "Kodihalli", "Indiranagar", "Domlur"],
    localNote: "Staying at The Leela Palace? We deliver premium vapes discreetly to your room or lobby in 30-45 minutes.",
  },
  {
    name: "ITC Gardenia Bangalore",
    slug: "itc-gardenia-bangalore",
    sublocations: ["Residency Road", "Richmond Circle", "MG Road", "Brigade Road", "Richmond Town"],
    localNote: "ITC Gardenia guests enjoy fast discreet vape delivery — straight to your room in under 45 minutes.",
  },
  {
    name: "Taj West End Bangalore",
    slug: "taj-west-end-bangalore",
    sublocations: ["Race Course Road", "Sadashivanagar", "Rajajinagar", "Malleswaram", "Seshadripuram"],
    localNote: "Near Taj West End? We deliver to your hotel or nearby location with full discretion guaranteed.",
  },
  {
    name: "JW Marriott Bangalore",
    slug: "jw-marriott-bangalore",
    sublocations: ["Vittal Mallya Road", "MG Road", "Brigade Road", "Lavelle Road", "Richmond Town"],
    localNote: "JW Marriott guests — order on WhatsApp and receive your vapes within 30-45 minutes, discreetly packaged.",
  },
  {
    name: "Oberoi Hotel Bangalore",
    slug: "oberoi-hotel-bangalore",
    sublocations: ["MG Road", "Brigade Road", "Lavelle Road", "Residency Road", "St Marks Road"],
    localNote: "The Oberoi Bangalore area is fully covered — fast delivery, sealed packaging, 100% original products.",
  },
  {
    name: "Conrad Bangalore",
    slug: "conrad-bangalore",
    sublocations: ["Vittal Mallya Road", "MG Road", "UB City", "Lavelle Road", "Richmond Town"],
    localNote: "Conrad Bangalore guests — get premium vapes delivered to your room in under 45 minutes.",
  },
  {
    name: "Hyatt Regency Bangalore",
    slug: "hyatt-regency-bangalore",
    sublocations: ["Old Airport Road", "HAL 2nd Stage", "Kodihalli", "Domlur", "Indiranagar"],
    localNote: "Hyatt Regency Bangalore — we cover your area with 30-45 min delivery and discreet packaging.",
  },
  {
    name: "Sheraton Grand Bangalore",
    slug: "sheraton-grand-bangalore",
    sublocations: ["Brigade Gateway", "Rajajinagar", "Malleswaram", "Yeshwanthpur", "Seshadripuram"],
    localNote: "Sheraton Grand at Brigade Gateway — fast vape delivery to your hotel or nearby address.",
  },
  {
    name: "St Regis Bangalore",
    slug: "st-regis-bangalore",
    sublocations: ["Residency Road", "Richmond Circle", "MG Road", "Lavelle Road", "Brigade Road"],
    localNote: "St Regis Bangalore guests — premium vapes delivered discreetly within 30-45 minutes.",
  },
  {
    name: "Four Seasons Bangalore",
    slug: "four-seasons-bangalore",
    sublocations: ["Yellahanka", "Hebbal", "Thanisandra", "Kogilu", "Jakkur"],
    localNote: "Four Seasons Bangalore — we deliver to your hotel with complete discretion and 100% original products.",
  },

  {
    name: "Hennur",
    slug: "hennur",
    sublocations: ["Kalyan Nagar", "HRBR Layout", "Banaswadi"
  {
    name: "Manyata Tech Park",
    slug: "manyata-tech-park",
    sublocations: ["Manyata Tech Park", "Hebbal", "Nagawara", "Thanisandra", "Yelahanka New Town"],
    localNote: "Working at Manyata Tech Park? Fast, discreet vape delivery to your office gate in 30-45 minutes.",
    area: "North Bangalore",
  },
  {
    name: "Bagmane Tech Park",
    slug: "bagmane-tech-park",
    sublocations: ["Bagmane Tech Park", "CV Raman Nagar", "Old Madras Road", "KR Puram", "Banaswadi"],
    localNote: "Near Bagmane Tech Park? We deliver vapes to your office or nearby address in 30-45 minutes.",
    area: "East Bangalore",
  },
  {
    name: "RMZ Infinity",
    slug: "rmz-infinity-bangalore",
    sublocations: ["RMZ Infinity", "Old Madras Road", "Banaswadi", "KR Puram", "CV Raman Nagar"],
    localNote: "Near RMZ Infinity IT Park? Fast delivery to your office or apartment in 30-45 minutes.",
    area: "East Bangalore",
  },
  {
    name: "Embassy Tech Village",
    slug: "embassy-tech-village",
    sublocations: ["Embassy Tech Village", "Devarabisanahalli", "Bellandur", "Outer Ring Road", "Sarjapur Road"],
    localNote: "Working at Embassy Tech Village? We deliver vapes to your office gate in 30-45 minutes.",
    area: "South Bangalore",
  },
  {
    name: "Prestige Tech Park",
    slug: "prestige-tech-park",
    sublocations: ["Prestige Tech Park", "Marathahalli", "Outer Ring Road", "Bellandur", "Kadubeesanahalli"],
    localNote: "Near Prestige Tech Park Marathahalli? Fast delivery to your office or apartment.",
    area: "East Bangalore",
  },
  {
    name: "ITPL",
    slug: "itpl-whitefield",
    sublocations: ["ITPL", "Whitefield", "Hope Farm", "Kadugodi", "Seetharampalya"],
    localNote: "Near ITPL Whitefield? Fast vape delivery to your office gate or apartment in 30-45 minutes.",
    area: "East Bangalore",
  },
  {
    name: "Cessna Business Park",
    slug: "cessna-business-park",
    sublocations: ["Cessna Business Park", "Kadubeesanahalli", "Marathahalli", "Outer Ring Road", "Bellandur"],
    localNote: "Near Cessna Business Park? Fast delivery to your office or nearby address.",
    area: "East Bangalore",
  },
  {
    name: "Apollo Hospital Bangalore",
    slug: "apollo-hospital-bangalore",
    sublocations: ["Bannerghatta Road", "JP Nagar", "Jayanagar", "BTM Layout", "Bilekahalli"],
    localNote: "Near Apollo Hospital Bannerghatta Road? Fast, discreet vape delivery in 30-45 minutes.",
    area: "South Bangalore",
  },
  {
    name: "Manipal Hospital",
    slug: "manipal-hospital-bangalore",
    sublocations: ["Old Airport Road", "HAL", "Indiranagar", "Domlur", "Kodihalli"],
    localNote: "Near Manipal Hospital Old Airport Road? We deliver to HAL and surrounding areas in 30-45 minutes.",
    area: "East Bangalore",
  },
  {
    name: "Fortis Hospital Bangalore",
    slug: "fortis-hospital-bangalore",
    sublocations: ["Bannerghatta Road", "JP Nagar", "Jayanagar", "Hulimavu", "BTM Layout"],
    localNote: "Near Fortis Hospital Bangalore? Fast, discreet vape delivery to Bannerghatta Road area.",
    area: "South Bangalore",
  },
  {
    name: "Narayana Health City",
    slug: "narayana-health-city",
    sublocations: ["Bommasandra", "Electronic City", "Attibele", "Chandapura", "Anekal"],
    localNote: "Near Narayana Health City? Fast delivery to Bommasandra and Electronic City area.",
    area: "South Bangalore",
  },
  {
    name: "Sakra World Hospital",
    slug: "sakra-world-hospital",
    sublocations: ["Devarabisanahalli", "Outer Ring Road", "Marathahalli", "Whitefield", "Bellandur"],
    localNote: "Near Sakra World Hospital? We deliver to Devarabisanahalli and surrounding areas.",
    area: "East Bangalore",
  },
  {
    name: "IISc Bangalore",
    slug: "iisc-bangalore",
    sublocations: ["IISc Campus", "Malleshwaram", "Rajajinagar", "Yeshwanthpur", "Sadashivanagar"],
    localNote: "Near IISc Bangalore? Fast, discreet vape delivery to the campus area and surroundings.",
    area: "North Bangalore",
  },
  {
    name: "Christ University",
    slug: "christ-university-bangalore",
    sublocations: ["Bannerghatta Road", "JP Nagar", "Hulimavu", "BTM Layout", "Jayanagar"],
    localNote: "Near Christ University? Fast delivery to Bannerghatta Road and student areas.",
    area: "South Bangalore",
  },
  {
    name: "RV College",
    slug: "rv-college-bangalore",
    sublocations: ["Mysore Road", "RV Niketan", "Rajajinagar", "Vijayanagar", "Basaveshwara Nagar"],
    localNote: "Near RV College Bangalore? Fast vape delivery to Mysore Road and surrounding areas.",
    area: "West Bangalore",
  },
  {
    name: "BMS College",
    slug: "bms-college-bangalore",
    sublocations: ["Bull Temple Road", "Basavanagudi", "Jayanagar", "Gandhi Bazaar", "NR Colony"],
    localNote: "Near BMS College Bangalore? Fast, discreet delivery to Basavanagudi and surroundings.",
    area: "South Bangalore",
  },
  {
    name: "Phoenix Marketcity",
    slug: "phoenix-marketcity-bangalore",
    sublocations: ["Whitefield", "ITPL Road", "Mahadevapura", "Kadugodi", "Hope Farm"],
    localNote: "Near Phoenix Marketcity Whitefield? Fast vape delivery to Whitefield and surroundings.",
    area: "East Bangalore",
  },
  {
    name: "Orion Mall",
    slug: "orion-mall-bangalore",
    sublocations: ["Rajajinagar", "Malleshwaram", "Yeshwanthpur", "Basaveshwara Nagar", "Vijayanagar"],
    localNote: "Near Orion Mall Rajajinagar? Fast delivery to Rajajinagar and West Bangalore areas.",
    area: "West Bangalore",
  },
  {
    name: "Forum Mall",
    slug: "forum-mall-bangalore",
    sublocations: ["Koramangala", "HSR Layout", "BTM Layout", "Ejipura", "Vivek Nagar"],
    localNote: "Near Forum Mall Koramangala? Fast vape delivery to Koramangala and surroundings.",
    area: "South Bangalore",
  },
  {
    name: "UB City",
    slug: "ub-city-bangalore",
    sublocations: ["Vittal Mallya Road", "MG Road", "Lavelle Road", "Richmond Road", "Cubbon Park"],
    localNote: "Near UB City Bangalore? Premium vape delivery to central Bangalore in 30-45 minutes.",
    area: "Central Bangalore",
  },
  {
    name: "Cunningham Road",
    slug: "cunningham-road-bangalore",
    sublocations: ["Cunningham Road", "Richmond Road", "Lavelle Road", "Residency Road", "MG Road"],
    localNote: "Cunningham Road premium corridor — fast, discreet vape delivery in 30-45 minutes.",
    area: "Central Bangalore",
  },
  {
    name: "Sadashivanagar",
    slug: "sadashivanagar-bangalore",
    sublocations: ["Sadashivanagar", "Palace Road", "Sankey Road", "Windsor Manor", "Dollars Colony"],
    localNote: "Sadashivanagar premium residential — discreet vape delivery to every address.",
    area: "North Bangalore",
  },
  {
    name: "Lavelle Road",
    slug: "lavelle-road-bangalore",
    sublocations: ["Lavelle Road", "Richmond Road", "Residency Road", "MG Road", "Vittal Mallya Road"],
    localNote: "Lavelle Road — Bangalore's luxury corridor. Discreet vape delivery in 30-45 minutes.",
    area: "Central Bangalore",
  },
  {
    name: "Frazer Town",
    slug: "frazer-town-bangalore",
    sublocations: ["Frazer Town", "Cooke Town", "Richards Town", "Cleveland Town", "Banaswadi"],
    localNote: "Frazer Town and surrounding areas — fast vape delivery in 30-45 minutes.",
    area: "East Bangalore",
  },
  {
    name: "Banaswadi",
    slug: "banaswadi-bangalore",
    sublocations: ["Banaswadi", "Ramamurthy Nagar", "HBR Layout", "Kalyan Nagar", "HRBR Layout"],
    localNote: "Banaswadi and North-East Bangalore — fast vape delivery to every society.",
    area: "East Bangalore",
  },
  {
    name: "Nagarbhavi",
    slug: "nagarbhavi-bangalore",
    sublocations: ["Nagarbhavi", "Kengeri", "Nayandahalli", "Uttarahalli", "Mysore Road"],
    localNote: "Nagarbhavi and West Bangalore — fast vape delivery to your door in 30-45 minutes.",
    area: "West Bangalore",
  },
  {
    name: "Yeshwanthpur",
    slug: "yeshwanthpur-bangalore",
    sublocations: ["Yeshwanthpur", "Rajajinagar", "Peenya", "Tumkur Road", "Chord Road"],
    localNote: "Yeshwanthpur and North-West Bangalore — fast, discreet vape delivery.",
    area: "North Bangalore",
  },
  {
    name: "Bannerghatta Road",
    slug: "bannerghatta-road",
    sublocations: ["Bannerghatta Road", "JP Nagar", "Gottigere", "Hulimavu", "Bilekahalli"],
    localNote: "Bannerghatta Road corridor — fast vape delivery to every apartment and office.",
    area: "South Bangalore",
  },
  {
    name: "Kanakapura Road",
    slug: "kanakapura-road",
    sublocations: ["Kanakapura Road", "JP Nagar", "Uttarahalli", "Gottigere", "Raghuvanahalli"],
    localNote: "Kanakapura Road — fast vape delivery to South Bangalore's growing residential zone.",
    area: "South Bangalore",
  },
  {
    name: "Old Airport Road",
    slug: "old-airport-road-bangalore",
    sublocations: ["Old Airport Road", "HAL", "Domlur", "Kodihalli", "Indiranagar"],
    localNote: "Old Airport Road — fast vape delivery to HAL and surrounding East Bangalore areas.",
    area: "East Bangalore",
  },
  {
    name: "Ulsoor",
    slug: "ulsoor-bangalore",
    sublocations: ["Ulsoor", "MG Road", "Halasuru", "Shivajinagar", "Vasanth Nagar"],
    localNote: "Ulsoor and Central Bangalore — fast, discreet vape delivery in 30-45 minutes.",
    area: "Central Bangalore",
  },
  {
    name: "Richmond Town",
    slug: "richmond-town-bangalore",
    sublocations: ["Richmond Town", "Lavelle Road", "Residency Road", "Langford Town", "Shanthala Nagar"],
    localNote: "Richmond Town premium area — discreet vape delivery to every building.",
    area: "Central Bangalore",
  },
  {
    name: "Basavanagudi",
    slug: "basavanagudi-bangalore",
    sublocations: ["Basavanagudi", "Gandhi Bazaar", "Bull Temple Road", "Hanumanthanagar", "VV Puram"],
    localNote: "Basavanagudi and South Central Bangalore — fast vape delivery in 30-45 minutes.",
    area: "South Bangalore",
  },
  {
    name: "Vijayanagar",
    slug: "vijayanagar-bangalore",
    sublocations: ["Vijayanagar", "Basaveshwara Nagar", "Nagarbhavi", "Mysore Road", "Chord Road"],
    localNote: "Vijayanagar and West Bangalore — fast vape delivery to every society.",
    area: "West Bangalore",
  },
  {
    name: "Kadugodi",
    slug: "kadugodi-bangalore",
    sublocations: ["Kadugodi", "Whitefield", "Hope Farm", "ITPL", "Seetharampalya"],
    localNote: "Kadugodi and Whitefield area — fast vape delivery to your door in 30-45 minutes.",
    area: "East Bangalore",
  },
  {
    name: "Thanisandra",
    slug: "thanisandra-bangalore",
    sublocations: ["Thanisandra", "Manyata Tech Park", "Nagawara", "Hebbal", "HBR Layout"],
    localNote: "Thanisandra and North Bangalore — fast delivery to every gated community.",
    area: "North Bangalore",
  },
  {
    name: "Devanahalli",
    slug: "devanahalli-bangalore",
    sublocations: ["Devanahalli", "Bangalore Airport Area", "KIADB Aerospace Park", "Bagalur", "Yelahanka"],
    localNote: "Near Devanahalli and Bangalore Airport? Fast vape delivery to North Bangalore.",
    area: "North Bangalore",
  },
  {
    name: "Tumkur Road",
    slug: "tumkur-road-bangalore",
    sublocations: ["Tumkur Road", "Peenya", "Yeshwanthpur", "Jalahalli", "Mathikere"],
    localNote: "Tumkur Road corridor — fast vape delivery to North-West Bangalore.",
    area: "North Bangalore",
  },
  {
    name: "Hosur Road",
    slug: "hosur-road-bangalore",
    sublocations: ["Hosur Road", "Electronic City", "Bommanahalli", "Singasandra", "Kudlu"],
    localNote: "Hosur Road and South Bangalore industrial corridor — fast vape delivery.",
    area: "South Bangalore",
  },
  {
    name: "Namma Metro Areas",
    slug: "namma-metro-bangalore",
    sublocations: ["MG Road", "Cubbon Park", "Majestic", "Yeshwanthpur", "Whitefield Metro"],
    localNote: "Near Namma Metro stations in Bangalore? Fast vape delivery across all Metro corridors.",
    area: "Central Bangalore",
  },
],
    localNote: "Hennur and its surrounding layouts are fully covered — Kalyan Nagar, HRBR, Banaswadi, all of it.",
  },
];

export function getLocationBySlug(slug: string): Location | undefined {
  return locations.find((l) => l.slug === slug);
}

export const WHATSAPP_URL =
  "https://wa.me/916282878843?text=Hi%20VapeDeliveryBangalore%2C%20I%20want%20to%20order%20a%20vape%20in%20Bangalore";

export const SHOP_URL =
  "/#products";
