import { SHOP_URL } from "./locations";

export interface Product {
  name: string;
  slug: string;
  puffs: string;
  price: string;
  originalPrice: string;
  discount: string;
  description: string;
  longDescription: string;
  flavourNote: string;
  badge: string;
  gradient: string;
  image: string;
  flavours: string[];
  brand: string;
  category: string;
  subCategory: string;
  features: string[];
  metaTitle: string;
  metaDescription: string;
  nicotine: string;
  inStock: boolean;
}

export const products: Product[] = [

  // ── ELFBAR — DISPOSABLE ──────────────────────────────────────────────────────
  {
    name: "Elfbar 600",
    slug: "elfbar-600",
    puffs: "600 Puffs",
    price: "₹999",
    originalPrice: "₹1,300",
    discount: "23% OFF",
    description: "Pink Grapefruit · 2ml · 20mg Nicotine Salt",
    longDescription: "The Elfbar 600 is the perfect entry-level disposable vape for beginners in Bangalore. Compact, light, and no-fuss — just open and vape. Available in fruity flavours with a smooth nicotine salt formula, it delivers consistent flavour across all 600 puffs. Ideal if you're trying vaping for the first time or want a pocket-sized option.",
    flavourNote: "Sweet citrus hit, perfect for beginners",
    badge: "BEGINNER PICK",
    gradient: "linear-gradient(135deg, #ec4899 0%, #f43f5e 100%)",
    image: "/products/elfbar-600.jpg",
    flavours: ["Pink Grapefruit", "Watermelon", "Blueberry", "Strawberry Ice", "Mango", "Peach Ice", "Grape"],
    brand: "Elfbar",
    category: "Vape",
    subCategory: "Disposable",
    features: ["600 Puffs", "2ml E-Liquid", "20mg Nicotine Salt", "Draw Activated", "No Charging Required", "Compact Design"],
    metaTitle: "Elfbar 600 Disposable Vape — Buy in Bangalore | ₹999 | VapeInBangalore",
    metaDescription: "Buy Elfbar 600 disposable vape in Bangalore at ₹999. Perfect beginner vape, 600 puffs, 7 flavours. 30-min delivery to BTM, HSR, Koramangala & 20+ areas.",
    nicotine: "20mg Nicotine Salt",
    inStock: true,
  },

  // ── ELFBAR — HIGH PUFF ───────────────────────────────────────────────────────
  {
    name: "Elfbar Raya D1",
    slug: "elfbar-raya-d1",
    puffs: "13,000 Puffs",
    price: "₹2,199",
    originalPrice: "₹2,599",
    discount: "15% OFF",
    description: "Watermelon Ice · Mesh Coil · Rechargeable",
    longDescription: "The Elfbar Raya D1 is the ideal everyday vape for Bangalore users who want reliable performance without the bulk. With 13,000 puffs, a mesh coil for smooth flavour delivery, and Type-C recharging, the D1 is built for consistent daily use. Whether you're in Koramangala, Whitefield, or HSR Layout — this delivers consistently from first puff to last.",
    flavourNote: "Juicy watermelon with icy menthol finish",
    badge: "FAST SELLING",
    gradient: "linear-gradient(135deg, #ff6b6b 0%, #ee5a24 100%)",
    image: "/products/raya-d1.jpg",
    flavours: ["Watermelon Ice", "Strawberry Kiwi", "Blueberry Ice", "Mango Peach", "Passion Fruit", "Lychee Ice", "Mixed Berries"],
    brand: "Elfbar",
    category: "Vape",
    subCategory: "High Puff",
    features: ["13,000 Puffs", "Mesh Coil", "Type-C Rechargeable", "20mg Nicotine Salt", "7 Flavours", "Compact Design"],
    metaTitle: "Elfbar Raya D1 — Buy in Bangalore | 13,000 Puffs | ₹2,199 | VapeInBangalore",
    metaDescription: "Buy Elfbar Raya D1 in Bangalore. 13,000 puffs, mesh coil, 7 flavours. 30-min delivery to BTM, HSR, Koramangala, Whitefield. ₹2,199.",
    nicotine: "20mg Nicotine Salt",
    inStock: true,
  },
  {
    name: "Elfbar Raya D3",
    slug: "elfbar-raya-d3",
    puffs: "25,000 Puffs",
    price: "₹2,799",
    originalPrice: "₹3,300",
    discount: "15% OFF",
    description: "Triple Mesh Coil · Smart Display · 3 Power Modes",
    longDescription: "The Elfbar Raya D3 is our bestselling vape in Bangalore. With 25,000 puffs, a smart display showing battery and puff count, and 3 adjustable power modes, the D3 gives you complete control. The triple mesh coil ensures consistent, rich flavour. Most popular in Whitefield, Electronic City, and Marathahalli.",
    flavourNote: "Rich fruity blends, massive puff count",
    badge: "FAST SELLING",
    gradient: "linear-gradient(135deg, #a855f7 0%, #6366f1 100%)",
    image: "/products/raya-d3.jpg",
    flavours: ["Watermelon Ice", "Blueberry Raspberry", "Peach Mango Watermelon", "Strawberry Ice", "Kiwi Passion Fruit", "Grape Ice", "Lemon Mint"],
    brand: "Elfbar",
    category: "Vape",
    subCategory: "High Puff",
    features: ["25,000 Puffs", "Triple Mesh Coil", "Smart LED Display", "3 Power Modes", "Type-C Rechargeable", "20mg Nicotine Salt"],
    metaTitle: "Elfbar Raya D3 — Buy in Bangalore | 25,000 Puffs | ₹2,799 | VapeInBangalore",
    metaDescription: "Buy Elfbar Raya D3 in Bangalore. 25,000 puffs, smart display, triple mesh coil. Best value vape. 30-min delivery. ₹2,799.",
    nicotine: "20mg Nicotine Salt",
    inStock: true,
  },
  {
    name: "Elfbar D3 Pro",
    slug: "elfbar-d3-pro",
    puffs: "30,000 Puffs",
    price: "₹2,799",
    originalPrice: "₹3,399",
    discount: "18% OFF",
    description: "Turbo Mode · Adjustable Airflow · Smart Display",
    longDescription: "The Elfbar D3 Pro pushes performance to the next level with 30,000 puffs, turbo mode for bigger clouds, and adjustable airflow for a personalised draw. The smart display keeps you updated on battery and puff count. The premium choice for experienced vapers in Bangalore who want maximum performance.",
    flavourNote: "Premium bold flavour, adjustable power",
    badge: "FAST SELLING",
    gradient: "linear-gradient(135deg, #f59e0b 0%, #ef4444 100%)",
    image: "/products/d3-pro.jpg",
    flavours: ["Blackcurrant Ice", "Watermelon Ice", "Blueberry Ice", "Mango Ice", "Strawberry Banana", "Grape Honeydew", "Cool Mint"],
    brand: "Elfbar",
    category: "Vape",
    subCategory: "High Puff",
    features: ["30,000 Puffs", "Turbo Mode", "Adjustable Airflow", "Smart Display", "Type-C Rechargeable", "Dual Mesh Coil"],
    metaTitle: "Elfbar D3 Pro — Buy in Bangalore | 30,000 Puffs | ₹2,799 | VapeInBangalore",
    metaDescription: "Buy Elfbar D3 Pro in Bangalore. 30,000 puffs, turbo mode, adjustable airflow. Premium vape with 30-min delivery. ₹2,799.",
    nicotine: "20mg Nicotine Salt",
    inStock: true,
  },
  {
    name: "Elfbar Ice King",
    slug: "elfbar-ice-king",
    puffs: "30,000 Puffs",
    price: "₹2,499",
    originalPrice: "₹3,500",
    discount: "29% OFF",
    description: "Watermelon Ice · 5-Level Coolness · 850mAh",
    longDescription: "The Elfbar Ice King is built for menthol lovers in Bangalore. With 5 levels of adjustable coolness, you control exactly how icy each puff feels. 30,000 puffs and an 850mAh battery ensure it lasts. The watermelon ice flavour is a Bangalore favourite — refreshing, intense, and consistently smooth.",
    flavourNote: "Ultra-icy watermelon, customisable chill",
    badge: "ONLY FEW LEFT",
    gradient: "linear-gradient(135deg, #06b6d4 0%, #3b82f6 100%)",
    image: "/products/ice-king.jpg",
    flavours: ["Watermelon Ice", "Blueberry Ice", "Strawberry Ice", "Mango Ice", "Grape Ice", "Lychee Ice"],
    brand: "Elfbar",
    category: "Vape",
    subCategory: "High Puff",
    features: ["30,000 Puffs", "5-Level Coolness Control", "850mAh Battery", "Type-C Rechargeable", "Dual Mesh Coil", "20mg Nicotine Salt"],
    metaTitle: "Elfbar Ice King — Buy in Bangalore | 30,000 Puffs | ₹2,499 | VapeInBangalore",
    metaDescription: "Buy Elfbar Ice King in Bangalore. 30,000 puffs, 5-level coolness, watermelon ice. Best menthol vape in Bangalore. ₹2,499.",
    nicotine: "20mg Nicotine Salt",
    inStock: true,
  },
  {
    name: "Elfbar BC 10000",
    slug: "elfbar-bc-10000",
    puffs: "10,000 Puffs",
    price: "₹2,199",
    originalPrice: "₹2,599",
    discount: "15% OFF",
    description: "Blueberry Mint · Mesh Coil · Type-C Rechargeable",
    longDescription: "The Elfbar BC 10000 combines elegant design with serious performance. 10,000 puffs in a sleek transparent body that shows the e-liquid level. The mesh coil delivers smooth, consistent flavour and the Type-C charging keeps you going. Popular across south Bangalore — BTM, Jayanagar, and JP Nagar.",
    flavourNote: "Fruity & icy blends, daily use favourite",
    badge: "FAST SELLING",
    gradient: "linear-gradient(135deg, #10b981 0%, #06b6d4 100%)",
    image: "/products/bc10000-v2.png",
    flavours: ["Blueberry Mint", "Watermelon Ice", "Strawberry Mango", "Kiwi Passion Fruit", "Peach Mango", "Grape Ice", "Cool Mint", "Lychee Watermelon"],
    brand: "Elfbar",
    category: "Vape",
    subCategory: "High Puff",
    features: ["10,000 Puffs", "Transparent Body", "Mesh Coil", "Type-C Rechargeable", "20mg Nicotine Salt", "8 Flavours"],
    metaTitle: "Elfbar BC 10000 — Buy in Bangalore | 10,000 Puffs | ₹2,199 | VapeInBangalore",
    metaDescription: "Buy Elfbar BC 10000 in Bangalore. 10,000 puffs, transparent design, mesh coil. 30-min delivery. ₹2,199.",
    nicotine: "20mg Nicotine Salt",
    inStock: true,
  },
  {
    name: "Elfbar Raya SOBO",
    slug: "elfbar-raya-sobo",
    puffs: "40,000 Puffs",
    price: "₹2,849",
    originalPrice: "₹3,499",
    discount: "19% OFF",
    description: "Interactive Game · Dual Mesh · 1100mAh · 5 Days Battery",
    longDescription: "The Elfbar Raya SOBO is the most advanced Elfbar ever available in Bangalore. With 40,000 puffs, an interactive game display, dual mesh coil, and a massive 1100mAh battery lasting up to 5 days — this is the ultimate vaping device. The gold-etched design makes it as premium as it performs.",
    flavourNote: "Bold, rich flavour — maximum puff count",
    badge: "NEW ARRIVAL",
    gradient: "linear-gradient(135deg, #f59e0b 0%, #78350f 100%)",
    image: "/products/raya-sobo.png",
    flavours: ["Watermelon Ice", "Mango Ice", "Blueberry Ice", "Strawberry Kiwi", "Grape Ice", "Lychee Ice", "Peach Mango"],
    brand: "Elfbar",
    category: "Vape",
    subCategory: "High Puff",
    features: ["40,000 Puffs", "Interactive Game Display", "1100mAh Battery", "Up to 5 Days Use", "Dual Mesh Coil", "Battery Level Mode"],
    metaTitle: "Elfbar Raya SOBO — Buy in Bangalore | 40,000 Puffs | ₹2,849 | VapeInBangalore",
    metaDescription: "Buy Elfbar Raya SOBO in Bangalore. 40,000 puffs, interactive display, 5-day battery. Most advanced Elfbar in Bangalore. ₹2,849.",
    nicotine: "20mg Nicotine Salt",
    inStock: true,
  },
  {
    name: "Elfbar Trio",
    slug: "elfbar-trio",
    puffs: "30,000 Puffs",
    price: "₹2,849",
    originalPrice: "₹3,499",
    discount: "19% OFF",
    description: "Smart Display · Nite Electronics · Dual Device",
    longDescription: "The Elfbar Trio brings a unique dual-device design to Bangalore. With a smart display, Nite Electronics technology, and 30,000 puffs, it's built for users who want something different. Available in two colour variants with rich fruity flavours and a consistent mesh coil system.",
    flavourNote: "Fruity blends with icy finish",
    badge: "NEW ARRIVAL",
    gradient: "linear-gradient(135deg, #6366f1 0%, #ec4899 100%)",
    image: "/products/elfbar-trio.png",
    flavours: ["Blueberry Ice", "Strawberry Kiwi", "Mango Ice", "Watermelon Ice", "Grape Ice", "Peach Ice"],
    brand: "Elfbar",
    category: "Vape",
    subCategory: "High Puff",
    features: ["30,000 Puffs", "Smart Display", "Nite Electronics", "Dual Mesh Coil", "Type-C Rechargeable", "20mg Nicotine Salt"],
    metaTitle: "Elfbar Trio — Buy in Bangalore | 30,000 Puffs | ₹2,849 | VapeInBangalore",
    metaDescription: "Buy Elfbar Trio in Bangalore. 30,000 puffs, smart display, unique dual design. 30-min delivery. ₹2,849.",
    nicotine: "20mg Nicotine Salt",
    inStock: true,
  },

  // ── ELFBAR — REFILL (NIC SALTS) ──────────────────────────────────────────────
  {
    name: "Elfliq Nic Salts",
    slug: "elfliq-nic-salts",
    puffs: "Refill Liquid",
    price: "₹1,599",
    originalPrice: "₹1,999",
    discount: "20% OFF",
    description: "Ice King · Taro Ice Cream · 30mg/ml · Powered by Elfbar",
    longDescription: "Elfliq Nic Salts are the official refill e-liquids from Elfbar — designed for pod systems and refillable devices. At 30mg/ml nicotine strength, they deliver a smooth, satisfying hit without harshness. The Ice King range features unique flavours like Taro Ice Cream — creamy, sweet, and subtly icy. Available for delivery across all Bangalore.",
    flavourNote: "Creamy taro with icy menthol — unique and smooth",
    badge: "REFILL LIQUID",
    gradient: "linear-gradient(135deg, #d97706 0%, #92400e 100%)",
    image: "/products/elfliq-nic-salt.png",
    flavours: ["Taro Ice Cream", "Watermelon Ice", "Blueberry Ice", "Strawberry Kiwi", "Mango Ice", "Lemon Mint"],
    brand: "Elfbar",
    category: "E-Liquid",
    subCategory: "Refill",
    features: ["30mg/ml Nicotine Salt", "10ml Bottle", "For Pod Systems", "Powered by Elfbar", "Ice King Series", "Smooth Hit"],
    metaTitle: "Elfliq Nic Salts — Buy in Bangalore | Elfbar Refill Liquid | ₹1,599 | VapeInBangalore",
    metaDescription: "Buy Elfliq Nic Salts in Bangalore. Official Elfbar refill liquid, 30mg nicotine salt. Taro Ice Cream & more. 30-min delivery. ₹1,599.",
    nicotine: "30mg/ml Nicotine Salt",
    inStock: true,
  },

  // ── IGET ────────────────────────────────────────────────────────────────────
  {
    name: "IGET Astro B18000",
    slug: "iget-astro-b18000",
    puffs: "18,000 Puffs",
    price: "₹2,199",
    originalPrice: "₹2,799",
    discount: "21% OFF",
    description: "18,000 Puffs · 13 Flavours · Dual Mesh Coil",
    longDescription: "The IGET Astro B18000 brings 18,000 puffs and 13 incredible flavours to Bangalore. With a dual mesh coil system for consistent flavour and a large capacity battery, the Astro is a serious contender for daily vapers. Available now for fast delivery across Bangalore including Electronic City, Whitefield, and Hebbal.",
    flavourNote: "Blueberry Watermelon — sweet and refreshing",
    badge: "FAST SELLING",
    gradient: "linear-gradient(135deg, #7dd3fc 0%, #6366f1 100%)",
    image: "/products/iget-astro.png",
    flavours: ["Blueberry Watermelon", "Watermelon Ice", "Mango Ice", "Strawberry Kiwi", "Peach Ice", "Grape Ice", "Lemon Mint", "Passion Fruit", "Lychee Ice", "Cool Mint"],
    brand: "IGET",
    category: "Vape",
    subCategory: "High Puff",
    features: ["18,000 Puffs", "13 Flavours", "Dual Mesh Coil", "Type-C Rechargeable", "Large Battery", "Draw Activated"],
    metaTitle: "IGET Astro B18000 — Buy in Bangalore | 18,000 Puffs | ₹2,199 | VapeInBangalore",
    metaDescription: "Buy IGET Astro B18000 in Bangalore. 18,000 puffs, 13 flavours, dual mesh coil. 30-min delivery. ₹2,199.",
    nicotine: "20mg Nicotine Salt",
    inStock: true,
  },

  // ── YUOTO ───────────────────────────────────────────────────────────────────
  {
    name: "Yuoto Beyonder",
    slug: "yuoto-beyonder",
    puffs: "7,000 Puffs",
    price: "₹1,789",
    originalPrice: "₹2,199",
    discount: "19% OFF",
    description: "7,000 Puffs · Watermelon Ice · Compact Design",
    longDescription: "The Yuoto Beyonder is a solid mid-range disposable vape available for delivery in Bangalore. 7,000 puffs in a compact, pocket-friendly form factor. The Watermelon Ice flavour is crisp and refreshing — perfect for Bangalore's warm weather. A great option for those looking for a reliable vape between the 600-puff entry level and the high-puff premium options.",
    flavourNote: "Crisp watermelon with cooling ice finish",
    badge: "GOOD VALUE",
    gradient: "linear-gradient(135deg, #ef4444 0%, #dc2626 100%)",
    image: "/products/yuoto-beyonder.png",
    flavours: ["Watermelon Ice", "Blueberry Ice", "Mango Ice", "Strawberry Kiwi", "Grape Ice", "Peach Ice"],
    brand: "Yuoto",
    category: "Vape",
    subCategory: "High Puff",
    features: ["7,000 Puffs", "Compact Design", "Type-C Rechargeable", "20mg Nicotine Salt", "Draw Activated", "Multiple Flavours"],
    metaTitle: "Yuoto Beyonder — Buy in Bangalore | 7,000 Puffs | ₹1,789 | VapeInBangalore",
    metaDescription: "Buy Yuoto Beyonder in Bangalore. 7,000 puffs, watermelon ice, compact design. 30-min delivery. ₹1,789.",
    nicotine: "20mg Nicotine Salt",
    inStock: true,
  },

  // ── POD SALT ─────────────────────────────────────────────────────────────────
  {
    name: "Pod Salt Hit The Spot",
    slug: "pod-salt-hit-the-spot",
    puffs: "35,000 Puffs",
    price: "₹2,699",
    originalPrice: "₹3,299",
    discount: "18% OFF",
    description: "35,000 Puffs · Fruity Flavours · Smart Battery Display",
    longDescription: "The Pod Salt Hit The Spot disposable is one of the highest puff-count devices available in Bangalore. With 35,000 puffs, a battery display, and rich fruity flavour profiles, it's built for vapers who want long-lasting performance. Available in multiple flavours and delivered fast across all of Bangalore.",
    flavourNote: "Mixed berry and tropical fruit blends",
    badge: "NEW ARRIVAL",
    gradient: "linear-gradient(135deg, #ec4899 0%, #f97316 100%)",
    image: "/products/pod-salt-disposable.png",
    flavours: ["Mixed Berry", "Mango Ice", "Strawberry Kiwi", "Watermelon Ice", "Blueberry Ice", "Peach Mango", "Grape Ice"],
    brand: "Pod Salt",
    category: "Vape",
    subCategory: "High Puff",
    features: ["35,000 Puffs", "Smart Battery Display", "Type-C Rechargeable", "20mg Nicotine Salt", "Multiple Flavours", "Ergonomic Design"],
    metaTitle: "Pod Salt Hit The Spot — Buy in Bangalore | 35,000 Puffs | ₹2,699 | VapeInBangalore",
    metaDescription: "Buy Pod Salt Hit The Spot in Bangalore. 35,000 puffs, battery display, fruity flavours. Fast 30-min delivery. ₹2,699.",
    nicotine: "20mg Nicotine Salt",
    inStock: true,
  },
  {
    name: "Pod Salt Core Nic Salt",
    slug: "pod-salt-core-nic-salt",
    puffs: "Refill Liquid",
    price: "₹1,599",
    originalPrice: "₹1,999",
    discount: "20% OFF",
    description: "Lemon & Lime Ice · 20mg/ml · For Pod Systems",
    longDescription: "Pod Salt Core is a premium nicotine salt e-liquid available for delivery in Bangalore. The Lemon & Lime Ice flavour is a citrusy, refreshing blend with a cool menthol finish — one of the most popular refill liquids among pod system users in Bangalore. Smooth 20mg nicotine salt formula for a satisfying hit without harshness.",
    flavourNote: "Zesty lemon lime with icy finish",
    badge: "REFILL LIQUID",
    gradient: "linear-gradient(135deg, #84cc16 0%, #ca8a04 100%)",
    image: "/products/pod-salt-core.png",
    flavours: ["Lemon & Lime Ice", "Mixed Berry", "Mango Ice", "Strawberry Kiwi", "Watermelon", "Blueberry"],
    brand: "Pod Salt",
    category: "E-Liquid",
    subCategory: "Refill",
    features: ["20mg/ml Nicotine Salt", "10ml Bottle", "For Pod Systems", "Smooth Hit", "Premium Formula", "Multiple Flavours"],
    metaTitle: "Pod Salt Core Nic Salt — Buy in Bangalore | Refill Liquid | ₹1,599 | VapeInBangalore",
    metaDescription: "Buy Pod Salt Core nicotine salt e-liquid in Bangalore. Lemon & Lime Ice, 20mg nicotine salt. Fast delivery. ₹1,599.",
    nicotine: "20mg/ml Nicotine Salt",
    inStock: true,
  },

  // ── NICOTINE POUCHES ─────────────────────────────────────────────────────────
  {
    name: "ZYN Cool Mint",
    slug: "zyn-cool-mint",
    puffs: "Nicotine Pouches",
    price: "₹999",
    originalPrice: "₹1,299",
    discount: "23% OFF",
    description: "Cool Mint · 6mg · 16 Pouches · Smoke-Free",
    longDescription: "ZYN Cool Mint nicotine pouches are the smokeless, vapeless way to enjoy nicotine in Bangalore. No smoke, no vapour — just place a pouch under your lip and enjoy a clean, refreshing mint sensation. 16 pouches per tin, 6mg nicotine strength. Perfect for offices, public spaces, and anywhere you can't vape.",
    flavourNote: "Clean, crisp mint — smoke-free nicotine",
    badge: "SMOKE-FREE",
    gradient: "linear-gradient(135deg, #06b6d4 0%, #0ea5e9 100%)",
    image: "/products/zyn-velo.png",
    flavours: ["Cool Mint"],
    brand: "ZYN",
    category: "Nicotine Pouches",
    subCategory: "Pouches",
    features: ["16 Pouches per Tin", "6mg Nicotine", "Smoke-Free", "Vapour-Free", "Discreet Use", "Cool Mint Flavour"],
    metaTitle: "ZYN Cool Mint Nicotine Pouches — Buy in Bangalore | ₹999 | VapeInBangalore",
    metaDescription: "Buy ZYN Cool Mint nicotine pouches in Bangalore. Smoke-free, vapour-free. 16 pouches, 6mg nicotine. Fast delivery. ₹999.",
    nicotine: "6mg Nicotine",
    inStock: true,
  },
  {
    name: "Velo Freezing Peppermint",
    slug: "velo-freezing-peppermint",
    puffs: "Nicotine Pouches",
    price: "₹999",
    originalPrice: "₹1,299",
    discount: "23% OFF",
    description: "Freezing Peppermint · Nicotine Pouches · Smoke-Free",
    longDescription: "Velo Freezing Peppermint nicotine pouches deliver an intense, icy peppermint experience without any smoke or vapour. A premium smoke-free alternative for nicotine users in Bangalore. Discreet, clean, and refreshing — place under your lip for a long-lasting mint hit. Great for offices, travel, and public spaces.",
    flavourNote: "Intense icy peppermint — long lasting",
    badge: "SMOKE-FREE",
    gradient: "linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)",
    image: "/products/zyn-velo.png",
    flavours: ["Freezing Peppermint"],
    brand: "Velo",
    category: "Nicotine Pouches",
    subCategory: "Pouches",
    features: ["Nicotine Pouches", "Smoke-Free", "Vapour-Free", "Freezing Peppermint", "Discreet Use", "Long Lasting"],
    metaTitle: "Velo Freezing Peppermint Pouches — Buy in Bangalore | ₹999 | VapeInBangalore",
    metaDescription: "Buy Velo Freezing Peppermint nicotine pouches in Bangalore. Smoke-free, intense peppermint. Fast delivery. ₹999.",
    nicotine: "Nicotine Pouches",
    inStock: true,
  },

  // ── TOBACCO ──────────────────────────────────────────────────────────────────
  {
    name: "Amber Leaf Rolling Tobacco",
    slug: "amber-leaf-tobacco",
    puffs: "50g",
    price: "₹999",
    originalPrice: "₹1,299",
    discount: "23% OFF",
    description: "Finest Virginia · Original Blend · 50g Rolling Tobacco",
    longDescription: "Amber Leaf is one of the most popular rolling tobaccos available in Bangalore. Made from finest Virginia tobacco with a smooth, balanced flavour. The original blend is mild and consistent — ideal for hand-rolling. Available for discreet, fast delivery across all major Bangalore areas.",
    flavourNote: "Smooth Virginia tobacco, balanced and mild",
    badge: "TOBACCO",
    gradient: "linear-gradient(135deg, #ca8a04 0%, #78350f 100%)",
    image: "/products/amber-leaf.png",
    flavours: ["Original Blend"],
    brand: "Amber Leaf",
    category: "Tobacco",
    subCategory: "Rolling Tobacco",
    features: ["50g Pack", "Finest Virginia Tobacco", "Original Blend", "For Hand Rolling", "Smooth Flavour", "Discreet Delivery"],
    metaTitle: "Amber Leaf Rolling Tobacco — Buy in Bangalore | 50g | ₹999 | VapeInBangalore",
    metaDescription: "Buy Amber Leaf rolling tobacco in Bangalore. 50g finest Virginia original blend. Fast discreet delivery. ₹999.",
    nicotine: "Tobacco",
    inStock: true,
  },
  {
    name: "Drum Bright Blue Tobacco",
    slug: "drum-bright-blue-tobacco",
    puffs: "50g",
    price: "₹999",
    originalPrice: "₹1,299",
    discount: "23% OFF",
    description: "Premium Quality · Bright Blue · 50g Rolling Tobacco",
    longDescription: "Drum Bright Blue is a premium rolling tobacco known for its smooth, consistent burn and balanced flavour. Available for fast delivery in Bangalore — ideal for those who prefer a lighter, more refined tobacco experience. Discreet packaging, fast dispatch.",
    flavourNote: "Light, smooth and consistent burn",
    badge: "TOBACCO",
    gradient: "linear-gradient(135deg, #3b82f6 0%, #1e40af 100%)",
    image: "/products/drum-blue.png",
    flavours: ["Bright Blue"],
    brand: "Drum",
    category: "Tobacco",
    subCategory: "Rolling Tobacco",
    features: ["50g Pack", "Premium Quality", "Bright Blue Blend", "Smooth Burn", "For Hand Rolling", "Discreet Delivery"],
    metaTitle: "Drum Bright Blue Rolling Tobacco — Buy in Bangalore | 50g | ₹999 | VapeInBangalore",
    metaDescription: "Buy Drum Bright Blue rolling tobacco in Bangalore. 50g premium quality. Fast discreet delivery. ₹999.",
    nicotine: "Tobacco",
    inStock: true,
  },
  {
    name: "Golden Virginia Tobacco",
    slug: "golden-virginia-tobacco",
    puffs: "50g",
    price: "₹999",
    originalPrice: "₹1,299",
    discount: "23% OFF",
    description: "The Original · Since 1877 · 50g Rolling Tobacco",
    longDescription: "Golden Virginia — The Original since 1877 — is one of the world's most respected rolling tobaccos. Now available for delivery in Bangalore. The rich, golden Virginia leaf delivers a full-bodied flavour with a smooth, even burn. Trusted by generations of tobacco enthusiasts worldwide.",
    flavourNote: "Full-bodied golden Virginia, rich and smooth",
    badge: "TOBACCO",
    gradient: "linear-gradient(135deg, #16a34a 0%, #ca8a04 100%)",
    image: "/products/golden-virginia.png",
    flavours: ["The Original"],
    brand: "Golden Virginia",
    category: "Tobacco",
    subCategory: "Rolling Tobacco",
    features: ["50g Pack", "Since 1877", "Golden Virginia Leaf", "Full-Bodied Flavour", "For Hand Rolling", "Discreet Delivery"],
    metaTitle: "Golden Virginia Tobacco — Buy in Bangalore | 50g | ₹999 | VapeInBangalore",
    metaDescription: "Buy Golden Virginia rolling tobacco in Bangalore. 50g original since 1877. Fast discreet delivery. ₹999.",
    nicotine: "Tobacco",
    inStock: true,
  },
  {
    name: "Natural American Spirit",
    slug: "natural-american-spirit-tobacco",
    puffs: "50g",
    price: "₹999",
    originalPrice: "₹1,299",
    discount: "23% OFF",
    description: "100% Additive-Free · Whole Leaf Tobacco · Natural Blend",
    longDescription: "Natural American Spirit is the choice for those who prefer 100% additive-free whole leaf tobacco. No additives, no flavours — just pure, natural tobacco. Available for delivery in Bangalore for those who appreciate an authentic, unadulterated tobacco experience. Smooth, clean, and natural.",
    flavourNote: "Pure, natural tobacco — no additives",
    badge: "TOBACCO",
    gradient: "linear-gradient(135deg, #0ea5e9 0%, #dc2626 100%)",
    image: "/products/american-spirit.png",
    flavours: ["Natural Blend"],
    brand: "American Spirit",
    category: "Tobacco",
    subCategory: "Rolling Tobacco",
    features: ["50g Pack", "100% Additive-Free", "Whole Leaf Tobacco", "No Artificial Flavours", "Natural Blend", "Discreet Delivery"],
    metaTitle: "Natural American Spirit Tobacco — Buy in Bangalore | 50g | ₹999 | VapeInBangalore",
    metaDescription: "Buy Natural American Spirit tobacco in Bangalore. 100% additive-free whole leaf tobacco. Fast delivery. ₹999.",
    nicotine: "Tobacco",
    inStock: true,
  },

  // ── LOST MARY ────────────────────────────────────────────────────────────────
  {
    name: "Lost Mary MT35000 Turbo",
    slug: "lost-mary-mt35000-turbo",
    puffs: "35,000 Puffs",
    price: "₹2,799",
    originalPrice: "₹3,499",
    discount: "20% OFF",
    description: "Turbo Mode · Smart Display · Mesh Coil · Ultra Long Lasting",
    longDescription: "The Lost Mary MT35000 Turbo is one of the most powerful disposable vapes available in Bangalore. With 35,000 puffs, turbo mode for maximum vapour production, and a smart display showing exact puff count and battery — this is built for serious vapers. Available for fast delivery across all Bangalore areas.",
    flavourNote: "Mixed tropical fruits with icy finish",
    badge: "NEW ARRIVAL",
    gradient: "linear-gradient(135deg, #06b6d4 0%, #6366f1 100%)",
    image: "/products/lost-mary-mt35000.png",
    flavours: ["Blueberry Ice", "Watermelon Ice", "Mango Ice", "Strawberry Kiwi", "Grape Ice", "Peach Ice", "Lychee Ice"],
    brand: "Lost Mary",
    category: "Vape",
    subCategory: "High Puff",
    features: ["35,000 Puffs", "Turbo Mode", "Smart Display", "Mesh Coil", "Rechargeable", "Ultra Long Lasting"],
    metaTitle: "Lost Mary MT35000 Turbo — Buy in Bangalore | 35,000 Puffs | ₹2,799 | VapeInBangalore",
    metaDescription: "Buy Lost Mary MT35000 Turbo in Bangalore. 35,000 puffs, turbo mode, smart display. Fast 30-min delivery. ₹2,799.",
    nicotine: "20mg Nicotine Salt",
    inStock: true,
  },
  {
    name: "Lost Mary MO10000",
    slug: "lost-mary-mo10000",
    puffs: "10,000 Puffs",
    price: "₹2,199",
    originalPrice: "₹2,799",
    discount: "21% OFF",
    description: "Mesh Coil · 18mg Nicotine · Smooth Flavour · Long Lasting",
    longDescription: "The Lost Mary MO10000 delivers 10,000 puffs of consistently smooth flavour thanks to its premium mesh coil. Available in bold, vibrant colours with matching fruity flavours — Strawberry Grapefruit, Blueberry, and more. A popular choice among Bangalore vapers looking for quality at a great price point.",
    flavourNote: "Strawberry grapefruit — bold, citrusy, smooth",
    badge: "FAST SELLING",
    gradient: "linear-gradient(135deg, #ef4444 0%, #a855f7 100%)",
    image: "/products/lost-mary-mo10000.png",
    flavours: ["Strawberry Grapefruit", "Blueberry Ice", "Watermelon Ice", "Mango Ice", "Strawberry Kiwi", "Grape Ice"],
    brand: "Lost Mary",
    category: "Vape",
    subCategory: "High Puff",
    features: ["10,000 Puffs", "Mesh Coil", "18mg Nicotine", "Smooth Flavour", "Long Lasting", "Multiple Colours"],
    metaTitle: "Lost Mary MO10000 — Buy in Bangalore | 10,000 Puffs | ₹2,199 | VapeInBangalore",
    metaDescription: "Buy Lost Mary MO10000 in Bangalore. 10,000 puffs, mesh coil, 18mg nicotine. Fast 30-min delivery. ₹2,199.",
    nicotine: "18mg Nicotine Salt",
    inStock: true,
  },

  // ── ELFBAR MOONNIGHT ─────────────────────────────────────────────────────────
  {
    name: "Elfbar MoonNight 40K",
    slug: "elfbar-moonnight-40k",
    puffs: "40,000 Puffs",
    price: "₹2,899",
    originalPrice: "₹3,599",
    discount: "19% OFF",
    description: "MoonNight Display · Coffee Flavour · 40,000 Puffs · Dual Mesh",
    longDescription: "The Elfbar MoonNight is a statement device — 40,000 puffs with a stunning animated moon display and Coffee as a standout flavour. The dual mesh coil delivers rich, full-bodied clouds with every puff. Available for delivery in Bangalore — the most visually striking Elfbar yet.",
    flavourNote: "Full Moon Coffee — rich, smooth, distinctive",
    badge: "NEW ARRIVAL",
    gradient: "linear-gradient(135deg, #312e81 0%, #7c3aed 100%)",
    image: "/products/elfbar-moonnight.png",
    flavours: ["Full Moon Coffee", "Watermelon Ice", "Blueberry Ice", "Mango Ice", "Grape Ice", "Strawberry Kiwi", "Peach Ice"],
    brand: "Elfbar",
    category: "Vape",
    subCategory: "High Puff",
    features: ["40,000 Puffs", "Animated Moon Display", "Dual Mesh Coil", "Battery Level Mode", "Type-C Rechargeable", "20mg Nicotine Salt"],
    metaTitle: "Elfbar MoonNight 40K — Buy in Bangalore | 40,000 Puffs | ₹2,899 | VapeInBangalore",
    metaDescription: "Buy Elfbar MoonNight in Bangalore. 40,000 puffs, animated moon display, coffee flavour. Fast delivery. ₹2,899.",
    nicotine: "20mg Nicotine Salt",
    inStock: true,
  },

  // ── NASTY ────────────────────────────────────────────────────────────────────
  {
    name: "Nasty Bolt WTF 50K",
    slug: "nasty-bolt-wtf-50k",
    puffs: "50,000 Puffs",
    price: "₹2,999",
    originalPrice: "₹3,799",
    discount: "21% OFF",
    description: "50,000 Puffs · 26ml · Dual Screen · Airflow Control · 3-Mode",
    longDescription: "The Nasty Bolt WTF is the highest puff-count vape available for delivery in Bangalore — 50,000 puffs with 26ml of e-liquid. Extra fast charging in under 25 minutes, airflow control for personalised draw, dual screens showing flavour and battery, and 3-mode selection. The ultimate device for serious vapers in Bangalore.",
    flavourNote: "Grape Ice and Blue Razz Lemonade — bold and electric",
    badge: "MOST POWERFUL",
    gradient: "linear-gradient(135deg, #7c3aed 0%, #eab308 100%)",
    image: "/products/nasty-bolt.png",
    flavours: ["Grape Ice", "Blue Razz Lemonade", "Watermelon Ice", "Mango Ice", "Strawberry Kiwi", "Peach Ice", "Lychee Ice"],
    brand: "Nasty",
    category: "Vape",
    subCategory: "High Puff",
    features: ["50,000 Puffs", "26ml E-Liquid", "Extra Fast Charging (<25min)", "1000mAh Battery", "Airflow Control", "Dual Screen", "3-Mode Selection", "Double Mesh Coil"],
    metaTitle: "Nasty Bolt WTF 50K — Buy in Bangalore | 50,000 Puffs | ₹2,999 | VapeInBangalore",
    metaDescription: "Buy Nasty Bolt WTF in Bangalore. 50,000 puffs, 26ml, dual screen, airflow control. Most powerful vape. ₹2,999.",
    nicotine: "20mg Nicotine Salt",
    inStock: true,
  },
];

export const shopUrl = SHOP_URL;

// ── Helpers ──────────────────────────────────────────────────────────────────
export const getProductsByBrand = (brand: string) =>
  products.filter(p => p.brand === brand);

export const getProductsByCategory = (category: string) =>
  products.filter(p => p.category === category);

export const getProductsBySubCategory = (sub: string) =>
  products.filter(p => p.subCategory === sub);

export const getRelatedProducts = (slug: string, limit = 3) => {
  const current = products.find(p => p.slug === slug);
  if (!current) return [];
  return products
    .filter(p => p.slug !== slug && (p.brand === current.brand || p.category === current.category))
    .slice(0, limit);
};
